version: 0.1

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 674212915813.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 674212915813.dkr.ecr.eu-west-2.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 674212915813.dkr.ecr.eu-west-2.amazonaws.com/youtube:latest
      - printf '[{"name":"fapptask","imageUri":"%s"}]'  674212915813.dkr.ecr.eu-west-2.amazonaws.com/youtube:latest  > imagedefinitions.json
artifacts:
  files: imagedefinitions.json



